name: CI

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  node-js:
    name: Node.js
    runs-on: ubuntu-latest
    concurrency: ci-nodejs-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Packages
        run: pnpm install

      - name: Build Client
        run: pnpm run build
        working-directory: ./client

      - name: Lint
        run: pnpm run lint
